// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cipher/decrypt": {
            "post": {
                "description": "Decrypts the provided ciphertext and returns the original plaintext.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cipher"
                ],
                "summary": "Decrypt",
                "parameters": [
                    {
                        "description": "Ciphertext to decrypt",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Decrypted text response",
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/cipher/encrypt": {
            "post": {
                "description": "Encrypts the provided plaintext and returns the ciphertext.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cipher"
                ],
                "summary": "Encrypt",
                "parameters": [
                    {
                        "description": "Plaintext to encrypt",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Encrypted text response",
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/GoCipher_internal_cipher.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GoCipher_internal_cipher.ErrResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Bad Request"
                },
                "processID": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "GoCipher_internal_cipher.Request": {
            "type": "object",
            "properties": {
                "profile": {
                    "type": "string",
                    "example": "default"
                },
                "value": {
                    "type": "string",
                    "example": "hello world"
                }
            }
        },
        "GoCipher_internal_cipher.Response": {
            "type": "object",
            "properties": {
                "processID": {
                    "type": "string",
                    "example": "123456789"
                },
                "profile": {
                    "type": "string",
                    "example": "default"
                },
                "value": {
                    "type": "string",
                    "example": "hello world"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "GoCipher",
	Description:      "API service that provides endpoints to encrypt and decrypt text.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
